# DB init
spring.sql.init.mode=always
spring.sql.init.platform=mysql

# DB
spring.datasource.platform=mysql
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/easyservice
spring.datasource.username=root
spring.datasource.password=
